### ISSUE TITLE
Add `log` action 

### ISSUE THREAD

**Issue by Bluscream** [exp111/VolumeLeveler#2]
```cpp
logMessage(config->reason.replace("{clid}", clientID).replace("{level}", userVolumeLevel).replace("{maxlevel}", config->level), LogLevel_DEBUG, ts3plugin_name(), serverConnectionHandlerID);
```

then i can use `onUserLoggingMessageEvent(self, logMessage, logLevel, logChannel, logID, logTime, completeLogString)` to catch it and do more advanced checking and actions

Off-Topic: @exp111bot ist das deiner auf telegram?

**Comment by Bluscream** [comment]
Maybe you can even make the `.replace("{clid}", clientID).replace("{level}", userVolumeLevel).replace("{maxlevel}", config->level)` global so these variables get replaced in the reasonstring for the other actions too.

**Comment by exp111** [comment]
That's actually a good idea to make some kind of api.

Wegen der Frage: Nein ich benutze Telegram erst seit einer Woche oder so und der Bot ist russisch 🤔. Ist aber ein seltener Name um den zu klauen^^
